import type { Metadata } from 'next'
import './globals.css'
import { languages } from '@/i18n/settings'
import { ChildProps } from '@/types'
import { Toaster } from '@/components/ui/sonner'
import { Sora, Poppins, Manrope } from 'next/font/google'

const sora = Sora({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700', '800'],
	variable: '--font-sora',
})

const manrope = Manrope({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	variable: '--font-manrope',
})
const poppins = Poppins({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	variable: '--font-poppins',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export async function generateStaticParams() {
	return languages.map(lng => ({ lng }))
}

interface Props extends ChildProps {
	params: {
		lng: string
	}
}

function RootLayout({ children, params: { lng } }: Props) {
	return (
		<html lang={lng} suppressHydrationWarning>
			<body
				className={`${sora.variable} ${manrope.variable} ${poppins.variable}  overflow-x-hidden antialiased`}
			>
				{children}
				<Toaster position='top-center' />
			</body>
		</html>
	)
}
export default RootLayout
